/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.danielecampogiani.minpathtriangle

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {

    @Test
    fun testReadLines() {

        val expected = listOf(
            listOf(7),
            listOf(6, 3),
            listOf(3, 8, 5),
            listOf(11, 2, 10, 9)
        )

        val actual = readLines("data.txt")
        assertEquals(expected, actual)
    }

    @Test
    fun testModelData() {

        val expected = buildFakeData()
        val actual = modelData(
            listOf(
                listOf(7),
                listOf(6, 3),
                listOf(3, 8, 5),
                listOf(11, 2, 10, 9)
            )
        )

        assertEquals(expected, actual)
    }

    @Test
    fun testMin() {
        val expected = 18
        val actual = findMin(buildFakeData())
        assertEquals(expected, actual)
    }

    @Test
    fun testMax() {
        val expected = 31
        val actual = findMax(buildFakeData())
        assertEquals(expected, actual)
    }

    private fun buildFakeData() = Parent(
        value = 7,
        left = Parent(
            value = 6,
            left = Parent(
                value = 3,
                left = Child(11),
                right = Child(2)
            ),
            right = Parent(
                value = 8,
                left = Child(2),
                right = Child(10)
            )
        ),
        right = Parent(
            value = 3,
            left = Parent(
                value = 8,
                left = Child(2),
                right = Child(10)
            ),
            right = Parent(
                value = 5,
                left = Child(10),
                right = Child(9)
            )
        )
    )
}
